In [40]:

import pandas as pd
from sklearn.model_selection import train_test_split

In [41]:

col_names = ['outlook', 'temp', 'humidity', 'windy',  'play']

PlayTennis=pd.read_csv("PlayTennis.csv",names=col_names,header=None)

PlayTennis.head(20)

     outlook  temp  humidity  windy  play
0    outlook  temp  humidity  windy  play
1      sunny   hot      high  false    no
2      sunny   hot      high   true    no
3   overcast   hot      high  false   yes
4      rainy  mild      high  false   yes
5      rainy  cool    normal  false   yes
6      rainy  cool    normal   true    no
7   overcast  cool    normal   true   yes
8      sunny  mild      high  false    no
9      sunny  cool    normal  false   yes
10     rainy  mild    normal  false   yes
11     sunny  mild    normal   true   yes
12  overcast  mild      high   true   yes
13  overcast   hot    normal  false   yes
14     rainy  mild      high   true    no

In [42]:
from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()

PlayTennis['outlook'] = Le.fit_transform(PlayTennis['outlook'])
PlayTennis['temp'] = Le.fit_transform(PlayTennis['temp'])
PlayTennis['humidity'] = Le.fit_transform(PlayTennis['humidity'])
PlayTennis['windy'] = Le.fit_transform(PlayTennis['windy'])
PlayTennis['play'] = Le.fit_transform(PlayTennis['play'])
PlayTennis

    outlook  temp  humidity  windy  play
0         0     3         1      2     1
1         3     1         0      0     0
2         3     1         0      1     0
3         1     1         0      0     2
4         2     2         0      0     2
5         2     0         2      0     2
6         2     0         2      1     0
7         1     0         2      1     2
8         3     2         0      0     0
9         3     0         2      0     2
10        2     2         2      0     2
11        3     2         2      1     2
12        1     2         0      1     2
13        1     1         2      0     2
14        2     2         0      1     0

In [34]:
col_names = ['outlook', 'temp', 'humidity', 'windy']

X = PlayTennis[col_names] # Features
y = PlayTennis.play # Target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100)

In [43]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [45]:
y_pred = model.predict(X_test)
y_pred

array([2, 0, 0, 2, 2])

In [47]:

from sklearn import metrics
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)

Gaussian Naive Bayes model accuracy(in %): 60.0